name: GitHub Actions saucedemo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out updates
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Update repo
        run: sudo apt-get update
      - name: Install software
        run: sudo apt-get install -y firefox
      - name: Firefox version
        run: firefox --version
      - name: Test with pytest
          run: |
            pytest


#test